### ISSUE TITLE
something  about the script of SPLITREADER-beta2.5_part2.sh

### ISSUE THREAD

**Issue by snowwwyyy** [baduelp/public#3]
Dear Baduel 
I am recently use your scripts to check TE inserion in our samples. but i have some questions  about SPLITREADER-beta2.5_part2.sh. For example , 

 'awk -v l=$LS ' $2-l>0 {print $1"\t"$2-l"\t"$3"\t"$4}' $TmpResultsDir/$in-$TE-disc-down.bed | $bedtoolsdir/intersectBed -a $TmpResultsDir/$in-insertion-sites.2 -b stdin -wa -wb | awk '($6+$7)>=r {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$12}' >> $OutputDir/$in-insertion-sites.bed  2>> $TmpDir/log.txt' 

 I have no idea about '($6+$7)>=r', i looked through the script and i did not understand the r's meaning . 

besides, 
'awk '$6<=$7 {print $1"\t"$6-4"\t"$7+4"\t"$4"\t"$5"\t"$2"\t"$3}' $TmpResultsDir/$in-$TE-disc-cluster.0 > $TmpResultsDir/$in-$TE-disc-cluster.1 2>> $TmpDir/log.txt
awk '$6>$7 {print $1"\t"$7-4"\t"$6+4"\t"$4"\t"$5"\t"$2"\t"$3}' $TmpResultsDir/$in-$TE-disc-cluster.0 >> $TmpResultsDir/$in-$TE-disc-cluster.1 2>> $TmpDir/log.txt'

I  also confused about '$6-4"\t"$7+4"，$7-4"\t"$6+4" in the script。why  is the number 4？

Sorry to waste your time 。and i hope to receive you reply。

**Comment by baduelp** [comment]
Dear Snowwwwyyy

Thanks for catching the 'r' leftover, it corresponds to a deprecated filter that is not defined anymore but should not have any impact on the output. We've removed it for clarity.

Regarding your second question about the 4, it is to avoid potential overlaps between discordant reads in + and - orientation resulting from bowtie2 forcing the alignment of mismatched bases at the end of the reads. Given the mapping parameters, we can expect up to 4bp overhanging from the mapping and that can artifically generate an overlap between clusters of + and - discordant reads. 
Hope this helps!
