### ISSUE TITLE
what sorfware used in origin align

### ISSUE THREAD

**Issue by Axolotl233** [baduelp/public#5]
Hi

i want to use your scripts to check TE inserion in our samples. but i confused what upstream align tools and parameters should be used?

now i have bam files generated by bwa-mem2 and bowtie2 with default parameter, if they can be used, which is prefer?

I will really appreciate it if you can give us some advice and some pieces of guidance

all bests
Nemo Wu

**Comment by baduelp** [comment]
Hi Nemo,
Sorry for the delay I had not seen your comment. We recommend using bowtie2 with default parameters as BWA-mem soft-clips  reads by default to improve mapping efficiency and as a result reads mapping partially over TEs won't be extracted properly by  SPLITREADER.
Hope this helps!
Pierre
