### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by ccmenard** [baduelp/public#6]
Hello!

I am trying to run this program and it seems the example run with Arabidposis is missing a script called "SPLITREADER-sort.sh". What is this script doing/can you upload it to the github? 

Thanks,

Claire

**Comment by baduelp** [comment]
My bad! Thank you for catching the omission, I've included it in the thaliana folder now. 
Hope this helps!
Pierre

**Comment by ccmenard** [comment]
Great, thank you.
